export enum Configuration {
    APP_PORT = 'APP_PORT',
    MYSQL_HOST = 'MYSQL_HOST',
    MYSQL_USERNAME = 'MYSQL_USERNAME',
    MYSQL_PASSWORD = 'MYSQL_PASSWORD',
    MYSQL_PORT = 'MYSQL_PORT',
    MYSQL_DATABASE = 'MYSQL_DATABASE',
    JWT_SECRET = 'JWT_SECRET',
    JWT_EXPIRE_IN = 'JWT_EXPIRE_IN'
}