export enum Configuration {
    PORT = 'PORT',
    HOST = 'HOST',
    USERNAME = 'USERNAME',
    PASSWORD = 'PASSWORD',
    PORTDATABASE = 'PORTDATABASE',
    DATABASE = 'DATABASE',
    JWT_SECRET = 'JWT_SECRET'
}